// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Http/HttpReqs/Proto_RegistReq.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Proto.ProtoInterface {

  /// <summary>Holder for reflection information generated from Http/HttpReqs/Proto_RegistReq.proto</summary>
  public static partial class ProtoRegistReqReflection {

    #region Descriptor
    /// <summary>File descriptor for Http/HttpReqs/Proto_RegistReq.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProtoRegistReqReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiNIdHRwL0h0dHBSZXFzL1Byb3RvX1JlZ2lzdFJlcS5wcm90bxoYRW51bXMv",
            "UHJvdG9fR2VuZGVyLnByb3RvGhZQcm90b19Nc2dSZXFJbmZvLnByb3RvIo0B",
            "Cg9Qcm90b19SZWdpc3RSZXESEAoIVXNlck5hbWUYASABKAkSEAoIUGFzc3dv",
            "cmQYAiABKAkSHQoGR2VuZGVyGAMgASgOMg0uUHJvdG9fR2VuZGVyEiUKCk1z",
            "Z1JlcUluZm8YBCABKAsyES5Qcm90b19Nc2dSZXFJbmZvEhAKCFRpbWVUaWNr",
            "GAUgASgSQheqAhRQcm90by5Qcm90b0ludGVyZmFjZWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Proto.ProtoInterface.ProtoGenderReflection.Descriptor, global::Proto.ProtoInterface.ProtoMsgReqInfoReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Proto.ProtoInterface.Proto_RegistReq), global::Proto.ProtoInterface.Proto_RegistReq.Parser, new[]{ "UserName", "Password", "Gender", "MsgReqInfo", "TimeTick" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Proto_RegistReq : pb::IMessage<Proto_RegistReq> {
    private static readonly pb::MessageParser<Proto_RegistReq> _parser = new pb::MessageParser<Proto_RegistReq>(() => new Proto_RegistReq());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Proto_RegistReq> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Proto.ProtoInterface.ProtoRegistReqReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Proto_RegistReq() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Proto_RegistReq(Proto_RegistReq other) : this() {
      userName_ = other.userName_;
      password_ = other.password_;
      gender_ = other.gender_;
      msgReqInfo_ = other.msgReqInfo_ != null ? other.msgReqInfo_.Clone() : null;
      timeTick_ = other.timeTick_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Proto_RegistReq Clone() {
      return new Proto_RegistReq(this);
    }

    /// <summary>Field number for the "UserName" field.</summary>
    public const int UserNameFieldNumber = 1;
    private string userName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string UserName {
      get { return userName_; }
      set {
        userName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Password" field.</summary>
    public const int PasswordFieldNumber = 2;
    private string password_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Password {
      get { return password_; }
      set {
        password_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Gender" field.</summary>
    public const int GenderFieldNumber = 3;
    private global::Proto.ProtoInterface.Proto_Gender gender_ = global::Proto.ProtoInterface.Proto_Gender.Boy;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Proto.ProtoInterface.Proto_Gender Gender {
      get { return gender_; }
      set {
        gender_ = value;
      }
    }

    /// <summary>Field number for the "MsgReqInfo" field.</summary>
    public const int MsgReqInfoFieldNumber = 4;
    private global::Proto.ProtoInterface.Proto_MsgReqInfo msgReqInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Proto.ProtoInterface.Proto_MsgReqInfo MsgReqInfo {
      get { return msgReqInfo_; }
      set {
        msgReqInfo_ = value;
      }
    }

    /// <summary>Field number for the "TimeTick" field.</summary>
    public const int TimeTickFieldNumber = 5;
    private long timeTick_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long TimeTick {
      get { return timeTick_; }
      set {
        timeTick_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Proto_RegistReq);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Proto_RegistReq other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UserName != other.UserName) return false;
      if (Password != other.Password) return false;
      if (Gender != other.Gender) return false;
      if (!object.Equals(MsgReqInfo, other.MsgReqInfo)) return false;
      if (TimeTick != other.TimeTick) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (UserName.Length != 0) hash ^= UserName.GetHashCode();
      if (Password.Length != 0) hash ^= Password.GetHashCode();
      if (Gender != global::Proto.ProtoInterface.Proto_Gender.Boy) hash ^= Gender.GetHashCode();
      if (msgReqInfo_ != null) hash ^= MsgReqInfo.GetHashCode();
      if (TimeTick != 0L) hash ^= TimeTick.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (UserName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(UserName);
      }
      if (Password.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Password);
      }
      if (Gender != global::Proto.ProtoInterface.Proto_Gender.Boy) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Gender);
      }
      if (msgReqInfo_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(MsgReqInfo);
      }
      if (TimeTick != 0L) {
        output.WriteRawTag(40);
        output.WriteSInt64(TimeTick);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (UserName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UserName);
      }
      if (Password.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Password);
      }
      if (Gender != global::Proto.ProtoInterface.Proto_Gender.Boy) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Gender);
      }
      if (msgReqInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MsgReqInfo);
      }
      if (TimeTick != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeSInt64Size(TimeTick);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Proto_RegistReq other) {
      if (other == null) {
        return;
      }
      if (other.UserName.Length != 0) {
        UserName = other.UserName;
      }
      if (other.Password.Length != 0) {
        Password = other.Password;
      }
      if (other.Gender != global::Proto.ProtoInterface.Proto_Gender.Boy) {
        Gender = other.Gender;
      }
      if (other.msgReqInfo_ != null) {
        if (msgReqInfo_ == null) {
          MsgReqInfo = new global::Proto.ProtoInterface.Proto_MsgReqInfo();
        }
        MsgReqInfo.MergeFrom(other.MsgReqInfo);
      }
      if (other.TimeTick != 0L) {
        TimeTick = other.TimeTick;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            UserName = input.ReadString();
            break;
          }
          case 18: {
            Password = input.ReadString();
            break;
          }
          case 24: {
            Gender = (global::Proto.ProtoInterface.Proto_Gender) input.ReadEnum();
            break;
          }
          case 34: {
            if (msgReqInfo_ == null) {
              MsgReqInfo = new global::Proto.ProtoInterface.Proto_MsgReqInfo();
            }
            input.ReadMessage(MsgReqInfo);
            break;
          }
          case 40: {
            TimeTick = input.ReadSInt64();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
