// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Proto_MsgResInfo.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Proto.ProtoInterface {

  /// <summary>Holder for reflection information generated from Proto_MsgResInfo.proto</summary>
  public static partial class ProtoMsgResInfoReflection {

    #region Descriptor
    /// <summary>File descriptor for Proto_MsgResInfo.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProtoMsgResInfoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZQcm90b19Nc2dSZXNJbmZvLnByb3RvGhpFbnVtcy9Qcm90b19FcnJvcklk",
            "cy5wcm90byJmChBQcm90b19Nc2dSZXNJbmZvEg8KB1N1Y2NlZWQYASABKAgS",
            "IAoHRXJyb3JJZBgCIAEoDjIPLlByb3RvX0Vycm9ySWRzEg0KBUVycm9yGAMg",
            "ASgJEhAKCFRpbWVUaWNrGAQgASgSQheqAhRQcm90by5Qcm90b0ludGVyZmFj",
            "ZWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Proto.ProtoInterface.ProtoErrorIdsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Proto.ProtoInterface.Proto_MsgResInfo), global::Proto.ProtoInterface.Proto_MsgResInfo.Parser, new[]{ "Succeed", "ErrorId", "Error", "TimeTick" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Proto_MsgResInfo : pb::IMessage<Proto_MsgResInfo> {
    private static readonly pb::MessageParser<Proto_MsgResInfo> _parser = new pb::MessageParser<Proto_MsgResInfo>(() => new Proto_MsgResInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Proto_MsgResInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Proto.ProtoInterface.ProtoMsgResInfoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Proto_MsgResInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Proto_MsgResInfo(Proto_MsgResInfo other) : this() {
      succeed_ = other.succeed_;
      errorId_ = other.errorId_;
      error_ = other.error_;
      timeTick_ = other.timeTick_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Proto_MsgResInfo Clone() {
      return new Proto_MsgResInfo(this);
    }

    /// <summary>Field number for the "Succeed" field.</summary>
    public const int SucceedFieldNumber = 1;
    private bool succeed_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Succeed {
      get { return succeed_; }
      set {
        succeed_ = value;
      }
    }

    /// <summary>Field number for the "ErrorId" field.</summary>
    public const int ErrorIdFieldNumber = 2;
    private global::Proto.ProtoInterface.Proto_ErrorIds errorId_ = global::Proto.ProtoInterface.Proto_ErrorIds.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Proto.ProtoInterface.Proto_ErrorIds ErrorId {
      get { return errorId_; }
      set {
        errorId_ = value;
      }
    }

    /// <summary>Field number for the "Error" field.</summary>
    public const int ErrorFieldNumber = 3;
    private string error_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Error {
      get { return error_; }
      set {
        error_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "TimeTick" field.</summary>
    public const int TimeTickFieldNumber = 4;
    private long timeTick_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long TimeTick {
      get { return timeTick_; }
      set {
        timeTick_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Proto_MsgResInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Proto_MsgResInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Succeed != other.Succeed) return false;
      if (ErrorId != other.ErrorId) return false;
      if (Error != other.Error) return false;
      if (TimeTick != other.TimeTick) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Succeed != false) hash ^= Succeed.GetHashCode();
      if (ErrorId != global::Proto.ProtoInterface.Proto_ErrorIds.None) hash ^= ErrorId.GetHashCode();
      if (Error.Length != 0) hash ^= Error.GetHashCode();
      if (TimeTick != 0L) hash ^= TimeTick.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Succeed != false) {
        output.WriteRawTag(8);
        output.WriteBool(Succeed);
      }
      if (ErrorId != global::Proto.ProtoInterface.Proto_ErrorIds.None) {
        output.WriteRawTag(16);
        output.WriteEnum((int) ErrorId);
      }
      if (Error.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Error);
      }
      if (TimeTick != 0L) {
        output.WriteRawTag(32);
        output.WriteSInt64(TimeTick);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Succeed != false) {
        size += 1 + 1;
      }
      if (ErrorId != global::Proto.ProtoInterface.Proto_ErrorIds.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ErrorId);
      }
      if (Error.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Error);
      }
      if (TimeTick != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeSInt64Size(TimeTick);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Proto_MsgResInfo other) {
      if (other == null) {
        return;
      }
      if (other.Succeed != false) {
        Succeed = other.Succeed;
      }
      if (other.ErrorId != global::Proto.ProtoInterface.Proto_ErrorIds.None) {
        ErrorId = other.ErrorId;
      }
      if (other.Error.Length != 0) {
        Error = other.Error;
      }
      if (other.TimeTick != 0L) {
        TimeTick = other.TimeTick;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Succeed = input.ReadBool();
            break;
          }
          case 16: {
            ErrorId = (global::Proto.ProtoInterface.Proto_ErrorIds) input.ReadEnum();
            break;
          }
          case 26: {
            Error = input.ReadString();
            break;
          }
          case 32: {
            TimeTick = input.ReadSInt64();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
