// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Enums/Proto_Gender.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Proto.ProtoInterface {

  /// <summary>Holder for reflection information generated from Enums/Proto_Gender.proto</summary>
  public static partial class ProtoGenderReflection {

    #region Descriptor
    /// <summary>File descriptor for Enums/Proto_Gender.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProtoGenderReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChhFbnVtcy9Qcm90b19HZW5kZXIucHJvdG8qIQoMUHJvdG9fR2VuZGVyEgcK",
            "A0JveRAAEggKBEdpcmwQAUIXqgIUUHJvdG8uUHJvdG9JbnRlcmZhY2ViBnBy",
            "b3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Proto.ProtoInterface.Proto_Gender), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum Proto_Gender {
    [pbr::OriginalName("Boy")] Boy = 0,
    [pbr::OriginalName("Girl")] Girl = 1,
  }

  #endregion

}

#endregion Designer generated code
