// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Http/HttpRess/Proto_CheckVersionRes.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Proto.ProtoInterface {

  /// <summary>Holder for reflection information generated from Http/HttpRess/Proto_CheckVersionRes.proto</summary>
  public static partial class ProtoCheckVersionResReflection {

    #region Descriptor
    /// <summary>File descriptor for Http/HttpRess/Proto_CheckVersionRes.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProtoCheckVersionResReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CilIdHRwL0h0dHBSZXNzL1Byb3RvX0NoZWNrVmVyc2lvblJlcy5wcm90bxoW",
            "UHJvdG9fTXNnUmVzSW5mby5wcm90byKkAQoVUHJvdG9fQ2hlY2tWZXJzaW9u",
            "UmVzEhUKDUx1YU5lZWRVcGRhdGUYASABKAgSFAoMQ1NOZWVkVXBkYXRlGAIg",
            "ASgIEhEKCUNTVmVyc2lvbhgDIAEoCRISCgpMdWFWZXJzaW9uGAQgASgJEiUK",
            "Ck1zZ1Jlc0luZm8YBSABKAsyES5Qcm90b19Nc2dSZXNJbmZvEhAKCFRpbWVU",
            "aWNrGAYgASgSQheqAhRQcm90by5Qcm90b0ludGVyZmFjZWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Proto.ProtoInterface.ProtoMsgResInfoReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Proto.ProtoInterface.Proto_CheckVersionRes), global::Proto.ProtoInterface.Proto_CheckVersionRes.Parser, new[]{ "LuaNeedUpdate", "CSNeedUpdate", "CSVersion", "LuaVersion", "MsgResInfo", "TimeTick" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Proto_CheckVersionRes : pb::IMessage<Proto_CheckVersionRes> {
    private static readonly pb::MessageParser<Proto_CheckVersionRes> _parser = new pb::MessageParser<Proto_CheckVersionRes>(() => new Proto_CheckVersionRes());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Proto_CheckVersionRes> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Proto.ProtoInterface.ProtoCheckVersionResReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Proto_CheckVersionRes() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Proto_CheckVersionRes(Proto_CheckVersionRes other) : this() {
      luaNeedUpdate_ = other.luaNeedUpdate_;
      cSNeedUpdate_ = other.cSNeedUpdate_;
      cSVersion_ = other.cSVersion_;
      luaVersion_ = other.luaVersion_;
      msgResInfo_ = other.msgResInfo_ != null ? other.msgResInfo_.Clone() : null;
      timeTick_ = other.timeTick_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Proto_CheckVersionRes Clone() {
      return new Proto_CheckVersionRes(this);
    }

    /// <summary>Field number for the "LuaNeedUpdate" field.</summary>
    public const int LuaNeedUpdateFieldNumber = 1;
    private bool luaNeedUpdate_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool LuaNeedUpdate {
      get { return luaNeedUpdate_; }
      set {
        luaNeedUpdate_ = value;
      }
    }

    /// <summary>Field number for the "CSNeedUpdate" field.</summary>
    public const int CSNeedUpdateFieldNumber = 2;
    private bool cSNeedUpdate_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool CSNeedUpdate {
      get { return cSNeedUpdate_; }
      set {
        cSNeedUpdate_ = value;
      }
    }

    /// <summary>Field number for the "CSVersion" field.</summary>
    public const int CSVersionFieldNumber = 3;
    private string cSVersion_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string CSVersion {
      get { return cSVersion_; }
      set {
        cSVersion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "LuaVersion" field.</summary>
    public const int LuaVersionFieldNumber = 4;
    private string luaVersion_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string LuaVersion {
      get { return luaVersion_; }
      set {
        luaVersion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "MsgResInfo" field.</summary>
    public const int MsgResInfoFieldNumber = 5;
    private global::Proto.ProtoInterface.Proto_MsgResInfo msgResInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Proto.ProtoInterface.Proto_MsgResInfo MsgResInfo {
      get { return msgResInfo_; }
      set {
        msgResInfo_ = value;
      }
    }

    /// <summary>Field number for the "TimeTick" field.</summary>
    public const int TimeTickFieldNumber = 6;
    private long timeTick_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long TimeTick {
      get { return timeTick_; }
      set {
        timeTick_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Proto_CheckVersionRes);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Proto_CheckVersionRes other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (LuaNeedUpdate != other.LuaNeedUpdate) return false;
      if (CSNeedUpdate != other.CSNeedUpdate) return false;
      if (CSVersion != other.CSVersion) return false;
      if (LuaVersion != other.LuaVersion) return false;
      if (!object.Equals(MsgResInfo, other.MsgResInfo)) return false;
      if (TimeTick != other.TimeTick) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (LuaNeedUpdate != false) hash ^= LuaNeedUpdate.GetHashCode();
      if (CSNeedUpdate != false) hash ^= CSNeedUpdate.GetHashCode();
      if (CSVersion.Length != 0) hash ^= CSVersion.GetHashCode();
      if (LuaVersion.Length != 0) hash ^= LuaVersion.GetHashCode();
      if (msgResInfo_ != null) hash ^= MsgResInfo.GetHashCode();
      if (TimeTick != 0L) hash ^= TimeTick.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (LuaNeedUpdate != false) {
        output.WriteRawTag(8);
        output.WriteBool(LuaNeedUpdate);
      }
      if (CSNeedUpdate != false) {
        output.WriteRawTag(16);
        output.WriteBool(CSNeedUpdate);
      }
      if (CSVersion.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(CSVersion);
      }
      if (LuaVersion.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(LuaVersion);
      }
      if (msgResInfo_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(MsgResInfo);
      }
      if (TimeTick != 0L) {
        output.WriteRawTag(48);
        output.WriteSInt64(TimeTick);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (LuaNeedUpdate != false) {
        size += 1 + 1;
      }
      if (CSNeedUpdate != false) {
        size += 1 + 1;
      }
      if (CSVersion.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CSVersion);
      }
      if (LuaVersion.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LuaVersion);
      }
      if (msgResInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MsgResInfo);
      }
      if (TimeTick != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeSInt64Size(TimeTick);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Proto_CheckVersionRes other) {
      if (other == null) {
        return;
      }
      if (other.LuaNeedUpdate != false) {
        LuaNeedUpdate = other.LuaNeedUpdate;
      }
      if (other.CSNeedUpdate != false) {
        CSNeedUpdate = other.CSNeedUpdate;
      }
      if (other.CSVersion.Length != 0) {
        CSVersion = other.CSVersion;
      }
      if (other.LuaVersion.Length != 0) {
        LuaVersion = other.LuaVersion;
      }
      if (other.msgResInfo_ != null) {
        if (msgResInfo_ == null) {
          MsgResInfo = new global::Proto.ProtoInterface.Proto_MsgResInfo();
        }
        MsgResInfo.MergeFrom(other.MsgResInfo);
      }
      if (other.TimeTick != 0L) {
        TimeTick = other.TimeTick;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            LuaNeedUpdate = input.ReadBool();
            break;
          }
          case 16: {
            CSNeedUpdate = input.ReadBool();
            break;
          }
          case 26: {
            CSVersion = input.ReadString();
            break;
          }
          case 34: {
            LuaVersion = input.ReadString();
            break;
          }
          case 42: {
            if (msgResInfo_ == null) {
              MsgResInfo = new global::Proto.ProtoInterface.Proto_MsgResInfo();
            }
            input.ReadMessage(MsgResInfo);
            break;
          }
          case 48: {
            TimeTick = input.ReadSInt64();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
