// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Tcp/TcpRess/Proto_TcpMsgBoxRes.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Proto.ProtoInterface {

  /// <summary>Holder for reflection information generated from Tcp/TcpRess/Proto_TcpMsgBoxRes.proto</summary>
  public static partial class ProtoTcpMsgBoxResReflection {

    #region Descriptor
    /// <summary>File descriptor for Tcp/TcpRess/Proto_TcpMsgBoxRes.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProtoTcpMsgBoxResReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiRUY3AvVGNwUmVzcy9Qcm90b19UY3BNc2dCb3hSZXMucHJvdG8aFlByb3Rv",
            "X01zZ1Jlc0luZm8ucHJvdG8ibQoSUHJvdG9fVGNwTXNnQm94UmVzEg0KBVRp",
            "dGxlGAEgASgJEg8KB0NvbnRlbnQYAiABKAkSJQoKTXNnUmVzSW5mbxgDIAEo",
            "CzIRLlByb3RvX01zZ1Jlc0luZm8SEAoIVGltZVRpY2sYBCABKBJCF6oCFFBy",
            "b3RvLlByb3RvSW50ZXJmYWNlYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Proto.ProtoInterface.ProtoMsgResInfoReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Proto.ProtoInterface.Proto_TcpMsgBoxRes), global::Proto.ProtoInterface.Proto_TcpMsgBoxRes.Parser, new[]{ "Title", "Content", "MsgResInfo", "TimeTick" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Proto_TcpMsgBoxRes : pb::IMessage<Proto_TcpMsgBoxRes> {
    private static readonly pb::MessageParser<Proto_TcpMsgBoxRes> _parser = new pb::MessageParser<Proto_TcpMsgBoxRes>(() => new Proto_TcpMsgBoxRes());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Proto_TcpMsgBoxRes> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Proto.ProtoInterface.ProtoTcpMsgBoxResReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Proto_TcpMsgBoxRes() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Proto_TcpMsgBoxRes(Proto_TcpMsgBoxRes other) : this() {
      title_ = other.title_;
      content_ = other.content_;
      msgResInfo_ = other.msgResInfo_ != null ? other.msgResInfo_.Clone() : null;
      timeTick_ = other.timeTick_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Proto_TcpMsgBoxRes Clone() {
      return new Proto_TcpMsgBoxRes(this);
    }

    /// <summary>Field number for the "Title" field.</summary>
    public const int TitleFieldNumber = 1;
    private string title_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Title {
      get { return title_; }
      set {
        title_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Content" field.</summary>
    public const int ContentFieldNumber = 2;
    private string content_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Content {
      get { return content_; }
      set {
        content_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "MsgResInfo" field.</summary>
    public const int MsgResInfoFieldNumber = 3;
    private global::Proto.ProtoInterface.Proto_MsgResInfo msgResInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Proto.ProtoInterface.Proto_MsgResInfo MsgResInfo {
      get { return msgResInfo_; }
      set {
        msgResInfo_ = value;
      }
    }

    /// <summary>Field number for the "TimeTick" field.</summary>
    public const int TimeTickFieldNumber = 4;
    private long timeTick_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long TimeTick {
      get { return timeTick_; }
      set {
        timeTick_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Proto_TcpMsgBoxRes);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Proto_TcpMsgBoxRes other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Title != other.Title) return false;
      if (Content != other.Content) return false;
      if (!object.Equals(MsgResInfo, other.MsgResInfo)) return false;
      if (TimeTick != other.TimeTick) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Title.Length != 0) hash ^= Title.GetHashCode();
      if (Content.Length != 0) hash ^= Content.GetHashCode();
      if (msgResInfo_ != null) hash ^= MsgResInfo.GetHashCode();
      if (TimeTick != 0L) hash ^= TimeTick.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Title.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Title);
      }
      if (Content.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Content);
      }
      if (msgResInfo_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(MsgResInfo);
      }
      if (TimeTick != 0L) {
        output.WriteRawTag(32);
        output.WriteSInt64(TimeTick);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Title.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Title);
      }
      if (Content.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Content);
      }
      if (msgResInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MsgResInfo);
      }
      if (TimeTick != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeSInt64Size(TimeTick);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Proto_TcpMsgBoxRes other) {
      if (other == null) {
        return;
      }
      if (other.Title.Length != 0) {
        Title = other.Title;
      }
      if (other.Content.Length != 0) {
        Content = other.Content;
      }
      if (other.msgResInfo_ != null) {
        if (msgResInfo_ == null) {
          MsgResInfo = new global::Proto.ProtoInterface.Proto_MsgResInfo();
        }
        MsgResInfo.MergeFrom(other.MsgResInfo);
      }
      if (other.TimeTick != 0L) {
        TimeTick = other.TimeTick;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Title = input.ReadString();
            break;
          }
          case 18: {
            Content = input.ReadString();
            break;
          }
          case 26: {
            if (msgResInfo_ == null) {
              MsgResInfo = new global::Proto.ProtoInterface.Proto_MsgResInfo();
            }
            input.ReadMessage(MsgResInfo);
            break;
          }
          case 32: {
            TimeTick = input.ReadSInt64();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
